data = load('epoxy_material_properties.csv');
time = data(:,1);
cmply = data(:,2);

[fitresult, gof] = power_law(time, cmply)

xvals = linspace(1,10^8,100);
yvals = fitresult(xvals);

figure(2)
plot(xvals,yvals.^-1)
xlabel('time')
ylabel('modulus mpa')
grid on
function [fitresult, gof] = power_law(time, cmply)
%CREATEFIT(TIME,CMPLY)
%  Create a fit.
%
%  Data for 'power_law' fit:
%      X Input : time
%      Y Output: cmply
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Jul-2021 16:24:55


%% Fit: 'power_law'.
[xData, yData] = prepareCurveData( time, cmply );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.000432208876966295 0.0284163070612118 2.09512696239809e-05];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'power_law' );
h = plot( fitresult, xData, yData );
legend( h, 'cmply vs. time', 'power_law', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'cmply', 'Interpreter', 'none' );
grid on
end